const DateConstants = {
  DATE_RECEIVED: 'DATE_RECEIVED',
  DATES_RECEIVED: 'DATES_RECEIVED',
  DATES_CLEARED: 'DATES_CLEARED',
  TODO_RECEIVED: 'DATE_TODO_RECEIVED',
  TODO_DELETED: 'DATE_TODO_DELETED'
}

export default DateConstants
