const ListConstants = {
  LISTS_RECEIVED: 'LISTS_RECEIVED',
  LIST_RECEIVED: 'LIST_RECEIVED',
  LIST_DELETED: 'LIST_DELETED',
	LISTS_CLEARED: 'LISTS_CLEARED',
	TODO_RECEIVED: 'TODO_RECEIVED',
	TODO_DELETED: 'TODO_DELETED'
};

export default ListConstants;
