const ListConstants = {
  LISTS_RECEIVED: 'LISTS_RECEIVED',
  LIST_RECEIVED: 'LIST_RECEIVED',
  LISTS_CLEARED: 'LISTS_CLEARED',
  LIST_DELETED: 'LIST_DELETED',
  TODO_RECEIVED: 'LIST_TODO_RECEIVED',
  TODO_DELETED: 'LIST_TODO_DELETED'
}

export default ListConstants
