const TodoConstants = {
  TODO_RECEIVED: 'TODO_RECEIVED',
  TODOS_RECEIVED: 'TODOS_RECEIVED',
  TODOS_RECEIVED_CALENDAR: 'TODOS_RECEIVED_CALENDAR',
  TODOS_CLEARED: 'TODOS_CLEARED'
};

export default TodoConstants;
